name: Deploy Stinkbait

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"
jobs:
  build:
    permissions:
      id-token: write
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
     
      - name: Install the zip
        run: |
          sudo apt-get update
          sudo apt-get install -y zip
      - name: Create Zip
        run: zip -r templates.zip templates/

      - name: Create Zip
        run: zip -r static.zip static/

      - name: Create Zip
        run: zip -r lambda_function.zip lambda_function.py

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          role-to-assume: arn:aws:iam::486694884707:role/github-action-role
          aws-region: us-east-1

      - name: Upload to S3
        run: aws s3 cp templates.zip s3://traingrclambdafunctiontest/

      - name: Upload to S3
        run: aws s3 cp static.zip s3://traingrclambdafunctiontest/

      - name: Upload to S3
        run: aws s3 cp lambda_function.zip s3://traingrclambdafunctiontest/

  deploy-stack:
    permissions:
      id-token: write
      contents: read
    runs-on: ubuntu-latest
    needs: build
    steps:

      - uses: actions/checkout@v3
      - name: Configure AWS Credential
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          role-to-assume: arn:aws:iam::225609042289:role/github-action-role
          aws-region: us-east-1

      - name: lambda-response-cloudformation
        run: aws cloudformation package --template-file template.yaml --s3-bucket traingrclambdafunctiontest --output-template-file proxy_templ.yaml --region us-east-1
      - name: Deploy the Lambda Function
        run:
          aws cloudformation deploy --template-file proxy_template.yaml --stack-name testStack --capabilities CAPABILITY_NAMED_IAM
