name: Deploy Stinkbait

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"
jobs:
  build:
    permissions:
      id-token: write
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install the zip
        run: |
          sudo apt-get update
          sudo apt-get install -y zip
          sudo apt-get install -y python3
          sudo apt-get install -y python3-pip

      - name: Pip Install Lambda Packages
        run: pip3 install -r requirements.txt -t ./packages --upgrade

      - name: Change Directory
        run: cd packages

      - name: Zip Packages
        run: zip -r ../lambda.zip .

      - name: Change Directory
        run: cd ..

      - name: Create Zip
        run: zip -r lambda.zip templates/

      - name: Create Zip
        run: zip -r lambda.zip static/

      - name: Create Zip
        run: zip -r lambda.zip lambda_function.py routes.py allow.py

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          role-to-assume: arn:aws:iam::225609042289:role/github-action-role
          aws-region: us-east-1

  deploy-stack:
    permissions:
      id-token: write
      contents: read
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          role-to-assume: arn:aws:iam::225609042289:role/github-action-role
          aws-region: us-east-1
      - name: Get stack events
        run: |
          aws cloudformation describe-stack-events --stack-name <stack-name> | grep "CREATE_FAILED" | tee >(cat >&2)
          echo $? # 0 if no failed events, 1 if there are failed events
      - name: Package Lambda Function Code
        run: aws cloudformation package --template-file template.yaml --s3-bucket stinkbait-225609042289 --output-template-file packaged_template.yaml --region us-east-1
      - name: Deploy the CloudFormation Stack
        run: aws cloudformation deploy --template-file proxy_template.yaml --stack-name stinkbait --capabilities CAPABILITY_NAMED_IAM
      - name: Get the Stack Output Information
        run: aws cloudformation describe-stacks --stack-name stinkbait --query "Stacks[0].Outputs" --output text