name: 'Deploy Stinkbait via CloudFormation'

# **What it does**: Renders the content of every page and check all internal links.
# **Why we have it**: To make sure all links connect correctly.
# **Who does it impact**: Docs content.

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read
  # Needed for the 'trilom/file-changes-action' action
  pull-requests: read

# This allows a subsequently queued workflow run to interrupt previous runs
concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  link-checker:
    runs-on: ubuntu-latest
    steps:
      - name: Zip the Repo Templates
        run: zip -r lambda.zip templates

      - name: Zip the Repo Static Files
        run: zip -r lambda.zip static

      - name: Zip the Lambda Function
        run: zip -r lambda.zip lambda_function.py

      - name: Upload the Lambda Function
        run: aws cloudformation package --template-file template.yaml --s3-bucket stinkbait --output-template-file packaged-template.yaml --region us-east-1

      - name: Deploy the Lambda Function
        run: aws cloudformation deploy --template-file packaged-template.yaml --stack-name stinkbait --capabilities CAPABILITY_IAM --region us-east-1